---
title: "TwitterCovid19S"
author: "Noah Berkowitz"
date: "April 15, 2020"
Class: "Geospatial R"
output: 
  html_document:
vignette: >
  %\VignetteIndexEntry{Project 1}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This RMD scrapes selected twitter accounts

## R Markdown

```{r, eval = FALSE}
install.packages("stringr")
install.packages("twitteR")
install.packages("purrr")
install.packages("tidytext")
install.packages("dplyr")
install.packages("tidyr")
install.packages("lubridate")
install.packages("scales")
install.packages("broom")
install.packages("ggplot2")
```

```{r, eval=FALSE}
library(stringr)
library(twitteR)
library(purrr)
library(tidytext)
library(dplyr)
library(tidyr)
library(lubridate)
library(scales)
library(broom)
library(ggplot2)
```

Get your Twitter Tokens!!! 

```{r, eval=FALSE}
consumerKey = "INSERT KEY HERE"
consumerSecret = "INSERT SECRET KEY HERE"
accessToken = "INSERT TOKEN HERE"
accessSecret = "INSERT SECRET TOKEN HERE"
options(httr_oauth_cache=TRUE)

setup_twitter_oauth(consumer_key = consumerKey, consumer_secret = consumerSecret,
access_token = accessToken, access_secret = accessSecret)
```
Lets get the account

```{r, eval=FALSE}
COVID19Accounts<- userTimeline("njgov", n = 3200)
COVID19Accounts_df <- tbl_df(map_df(COVID19Accounts, as.data.frame))
write.csv(COVID19Accounts_df, "GoAccountsv.csv")
```
Lets find all tweets that have a certain COVID related #

```{r, eval=FALSE}
policys <- searchTwitter("#closure exclude:retweets", n=3200)
policys_df <- tbl_df(map_df(policys, as.data.frame))
write.csv(policys_df, "policys.csv")
```

Lets scrape feedback..retweets

```{r, eval= FALSE}
tweetstoCOVID19Accounts <- searchTwitter("@njgov exclude:retweets", n=3200)
tweetstoCOVID19Account_df <- tbl_df(map_df(tweetstoCOVID19Accounts, as.data.frame))
write.csv(tweetstoCOVID19Account_df, "tweetstoCOVID19Accounts.csv")
```

