---
title: "Data Extraction"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{dataextract}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, echo=FALSE, include=FALSE}
# install.packages("pdftools")
# install.packages("tidytext")
library(covid19interventions)
library(tidyverse)
library(pdftools)
library(tidytext)
library(dplyr)
library(tidyr)
library(rvest)
```

## Web Scraping Method
```{r}
# executive order posted
order <- xml2::read_html("https://www.governor.ny.gov/news/governor-cuomo-issues-guidance-essential-services-under-new-york-state-pause-executive-order")

# identify html tag to scrape
order_txt <- order %>%
  html_node("div.content") %>%
  html_text()
```

## PDF Extraction Method
```{r}
# order in PDF format
pdf_file <- "https://www.como.gov/wp-content/uploads/Special-Order-2020-03-Stay-at-Home-Order-Issued-3-24-2020-FAQ-2.pdf"
order_txt <- pdf_text(pdf_file)
```

## Data Cleanup & Formatting
```{r}
order_txt <- unlist(strsplit(order_txt,"[ \t\r\n\\,\\.]"))
order_txt <- order_txt[order_txt != ""]

# convert to dataframe
order_tbl <- as.data.frame(order_txt)
names(order_tbl) <- "word"
```


## Bigram Creation using tidytext
```{r}
# unnest_tokens splits column into tokens
# token = unit of text, in this case a word
bigrams <- order_tbl %>%
  unnest_tokens(output = word, input = word, token = "ngrams", n = 2)

# separate words column into multiple columns using " " as separator
bigrams_separated <- bigrams %>%
  separate(word, c("word1", "word2"), sep = " ")

# remove stop words- of, if, else
# not useful for analysis
bigrams_filtered <- bigrams_separated %>%
  filter(!word1 %in% stop_words$word) %>%
  filter(!word2 %in% stop_words$word)

# # count frequency of words occuring together
# bigram_counts <- bigrams_filtered %>% 
#   count(word1, word2, sort = TRUE)

# adjacent two-words frequency
# --NOT TOO MEANINGFUL--
bigrams_separated %>%
  filter(word1 == "essential") %>%
  count(word1, word2, sort = TRUE)
```
